# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybT5MNDjx9pM1apxWG2u-ljUFV6v4Ihw
"""

# ============================================================
# LIGHTWEIGHT ML-BASED IDS FOR IOT ENVIRONMENTS
# MEMORY-OPTIMIZED
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os
import time
import glob
import joblib
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    RocCurveDisplay
)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

warnings.filterwarnings("ignore")

# ============================================================
# CONFIG
# ============================================================

BASE_DATASET_PATH = "/content/drive/MyDrive/CICIOT23"
TARGET_COLUMN = "label"

TEST_SIZE = 0.2
RANDOM_STATE = 42
TOP_K_FEATURES = 20

# much smaller sample to avoid Colab crash
ROWS_PER_FILE = 100000

OUTPUT_DIR = Path("/content/outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

# ============================================================
# HELPERS
# ============================================================

def load_sampled_cic_iot2023_dataset(base_path: str, rows_per_file: int = 100000) -> pd.DataFrame:
    """
    Load a manageable sample from each file instead of loading everything.
    """
    csv_files = glob.glob(os.path.join(base_path, "**", "*.csv"), recursive=True)
    parquet_files = glob.glob(os.path.join(base_path, "**", "*.parquet"), recursive=True)
    all_files = csv_files + parquet_files

    if len(all_files) == 0:
        raise FileNotFoundError(f"No CSV or parquet files found under: {base_path}")

    print(f"Found {len(all_files)} files.\n")

    dfs = []

    for file in all_files:
        filename = os.path.basename(file).lower()

        if "copy of" in filename:
            print(f"Skipping duplicate file: {file}")
            continue

        try:
            if file.lower().endswith(".csv"):
                df = pd.read_csv(file)
            else:
                df = pd.read_parquet(file)

            df.columns = df.columns.str.strip()

            if len(df) > rows_per_file:
                df = df.sample(n=rows_per_file, random_state=RANDOM_STATE)

            dfs.append(df)
            print(f"Loaded sampled: {file} -> {df.shape}")

        except Exception as e:
            print(f"Skipping: {file} | Error: {e}")

    if len(dfs) == 0:
        raise ValueError("No files could be loaded.")

    full_df = pd.concat(dfs, ignore_index=True)
    full_df.columns = full_df.columns.str.strip()

    print(f"\nCombined sampled dataset shape: {full_df.shape}")
    return full_df


def find_target_column(df: pd.DataFrame, preferred_target: str = "label") -> str:
    possible_targets = [
        preferred_target, "label", "Label", "labels", "Labels",
        "Attack", "attack", "Class", "class"
    ]

    df_cols_lower = {col.lower(): col for col in df.columns}

    for col in possible_targets:
        if col.lower() in df_cols_lower:
            actual_col = df_cols_lower[col.lower()]
            print(f"Using target column: {actual_col}")
            return actual_col

    raise ValueError(f"Could not find target column. Columns: {df.columns.tolist()}")


def inspect_dataset(df: pd.DataFrame, target_col: str):
    print("\n===== DATASET OVERVIEW =====")
    print("Shape:", df.shape)
    print("\nTarget value counts:")
    print(df[target_col].value_counts(dropna=False).head(30))
    print("\nMissing values (top 10):")
    print(df.isna().sum().sort_values(ascending=False).head(10))


def clean_dataset(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
    df = df.copy()
    df.columns = df.columns.str.strip()

    raw_labels = df[target_col].astype(str).str.strip()
    print("\n===== RAW LABELS BEFORE BINARY MAPPING =====")
    print(raw_labels.value_counts().head(50))

    raw_labels_lower = raw_labels.str.lower()
    df[target_col] = raw_labels_lower.apply(lambda x: 0 if "benign" in x else 1)

    before = len(df)
    df = df.drop_duplicates()
    after = len(df)
    print(f"\nRemoved duplicates: {before - after}")

    df = df.replace([np.inf, -np.inf], np.nan)

    print("\n===== TARGET DISTRIBUTION AFTER CLEANING =====")
    print(df[target_col].value_counts())

    return df


def split_features_target(df: pd.DataFrame, target_col: str):
    X = df.drop(columns=[target_col])
    y = df[target_col]
    return X, y


def keep_numeric_features_only(X: pd.DataFrame):
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    X_numeric = X[numeric_cols].copy()
    return X_numeric, numeric_cols


def preprocess_features(X_train: pd.DataFrame, X_test: pd.DataFrame):
    numeric_cols = X_train.columns.tolist()

    imputer = SimpleImputer(strategy="median")
    scaler = StandardScaler()

    X_train_imputed = imputer.fit_transform(X_train)
    X_test_imputed = imputer.transform(X_test)

    X_train_scaled = scaler.fit_transform(X_train_imputed)
    X_test_scaled = scaler.transform(X_test_imputed)

    return X_train_scaled, X_test_scaled, numeric_cols, imputer, scaler


def mrmr_style_feature_selection(X_train, y_train, X_test, feature_names, top_k=20):
    mi_scores = mutual_info_classif(X_train, y_train, random_state=RANDOM_STATE)
    ranked_idx = np.argsort(mi_scores)[::-1][:top_k]

    selected_features = [feature_names[i] for i in ranked_idx]
    X_train_sel = X_train[:, ranked_idx]
    X_test_sel = X_test[:, ranked_idx]

    feature_df = pd.DataFrame({
        "Feature": feature_names,
        "MI_Score": mi_scores
    }).sort_values(by="MI_Score", ascending=False)

    feature_df.to_csv(OUTPUT_DIR / "feature_scores.csv", index=False)

    return X_train_sel, X_test_sel, selected_features, feature_df


def false_positive_rate(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    return fp / (fp + tn) if (fp + tn) > 0 else 0.0


def evaluate_model(model, X_train, y_train, X_test, y_test, model_name):
    start_train = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - start_train

    start_infer = time.time()
    y_pred = model.predict(X_test)
    infer_time = time.time() - start_infer

    y_prob = None
    roc_auc = np.nan

    if hasattr(model, "predict_proba"):
        probs = model.predict_proba(X_test)
        if probs.shape[1] > 1:
            y_prob = probs[:, 1]
            roc_auc = roc_auc_score(y_test, y_prob)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    fpr = false_positive_rate(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

    model_file = OUTPUT_DIR / f"{model_name}.joblib"
    joblib.dump(model, model_file)
    model_size_kb = os.path.getsize(model_file) / 1024

    results = {
        "Model": model_name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1,
        "False Positive Rate": fpr,
        "ROC-AUC": roc_auc,
        "Training Time (s)": train_time,
        "Inference Time (s)": infer_time,
        "Model Size (KB)": model_size_kb
    }

    return results, y_pred, y_prob, cm


def plot_confusion_matrix(cm, model_name):
    disp = ConfusionMatrixDisplay(confusion_matrix=np.array(cm), display_labels=["Benign", "Attack"])
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix - {model_name}")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{model_name}_confusion_matrix.png")
    plt.show()


def plot_roc_curve(y_test, y_prob, model_name):
    if y_prob is None:
        return
    RocCurveDisplay.from_predictions(y_test, y_prob)
    plt.title(f"ROC Curve - {model_name}")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{model_name}_roc_curve.png")
    plt.show()


# ============================================================
# MAIN
# ============================================================

def main():
    df = load_sampled_cic_iot2023_dataset(BASE_DATASET_PATH, rows_per_file=ROWS_PER_FILE)

    actual_target_col = find_target_column(df, TARGET_COLUMN)
    inspect_dataset(df, actual_target_col)

    df = clean_dataset(df, actual_target_col)

    if df[actual_target_col].nunique() < 2:
        raise ValueError("Still only one class after cleaning.")

    X, y = split_features_target(df, actual_target_col)
    X, numeric_cols = keep_numeric_features_only(X)

    print(f"\nUsing {len(numeric_cols)} numeric features.")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=y
    )

    print("\nTrain shape:", X_train.shape)
    print("Test shape:", X_test.shape)

    X_train_processed, X_test_processed, feature_names, imputer, scaler = preprocess_features(X_train, X_test)

    joblib.dump(imputer, OUTPUT_DIR / "imputer.joblib")
    joblib.dump(scaler, OUTPUT_DIR / "scaler.joblib")

    X_train_sel, X_test_sel, selected_features, feature_df = mrmr_style_feature_selection(
        X_train_processed, y_train, X_test_processed, feature_names, top_k=TOP_K_FEATURES
    )

    print("\n===== SELECTED FEATURES =====")
    for i, f in enumerate(selected_features, start=1):
        print(f"{i}. {f}")

    models = {
        "DecisionTree": DecisionTreeClassifier(max_depth=8, random_state=RANDOM_STATE),
        "RandomForest": RandomForestClassifier(n_estimators=100, max_depth=12, random_state=RANDOM_STATE, n_jobs=-1),
        "LogisticRegression": LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
        "GradientBoosting": GradientBoostingClassifier(n_estimators=50, learning_rate=0.1, max_depth=3, random_state=RANDOM_STATE)
    }

    results = []

    for model_name, model in models.items():
        print(f"\n===== TRAINING {model_name} =====")
        result, y_pred, y_prob, cm = evaluate_model(
            model, X_train_sel, y_train, X_test_sel, y_test, model_name
        )

        results.append(result)

        print(f"\nResults for {model_name}:")
        for key, value in result.items():
            print(f"{key}: {value}")

        plot_confusion_matrix(cm, model_name)
        plot_roc_curve(y_test, y_prob, model_name)

    results_df = pd.DataFrame(results)
    results_df.to_csv(OUTPUT_DIR / "model_results.csv", index=False)

    print("\n===== FINAL RESULTS TABLE =====")
    print(results_df.sort_values(by="F1", ascending=False))
    results.append(result)
    if model_name == "GradientBoosting":
      joblib.dump(model, "gb_ids_model.pkl")

  # Create deployment sample
    sample_data = pd.DataFrame(X_test_sel[:10], columns=selected_features)

    # Save actual labels
    sample_labels = pd.DataFrame(y_test.iloc[:10].values, columns=["Actual_Label"])

    # Export files
    sample_data.to_csv("deployment_test.csv", index=False)
    sample_labels.to_csv("deployment_labels.csv", index=False)

    print("Deployment files created!")

if __name__ == "__main__":
    main()
