# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybT5MNDjx9pM1apxWG2u-ljUFV6v4Ihw
"""

# ============================================================
# LIGHTWEIGHT ML-BASED IDS FOR IOT ENVIRONMENTS
# Full Google Colab + Google Drive Version
# Dataset: CIC-IoT2023
# Path used: /content/drive/MyDrive/CICIOT23
# ============================================================

# ---------------------------
# 0. MOUNT GOOGLE DRIVE
# ---------------------------
from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# 1. IMPORTS
# ============================================================

import os
import time
import glob
import joblib
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    RocCurveDisplay
)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

warnings.filterwarnings("ignore")

# ============================================================
# 2. CONFIGURATION
# ============================================================

BASE_DATASET_PATH = "/content/drive/MyDrive/CICIOT23"
TARGET_COLUMN = "label"

TEST_SIZE = 0.2
RANDOM_STATE = 42
TOP_K_FEATURES = 20

# Sampling helps a lot with runtime/memory in Colab
USE_SAMPLING = True
SAMPLE_FRAC = 0.10   # 10% from each class after cleaning

OUTPUT_DIR = Path("/content/outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

# ============================================================
# 3. HELPERS
# ============================================================

def load_cic_iot2023_dataset(base_path: str) -> pd.DataFrame:
    """
    Load and merge all CSV or parquet files inside the dataset folders.
    Skips obvious duplicate files like 'Copy of ...'.
    """
    csv_files = glob.glob(os.path.join(base_path, "**", "*.csv"), recursive=True)
    parquet_files = glob.glob(os.path.join(base_path, "**", "*.parquet"), recursive=True)
    all_files = csv_files + parquet_files

    if len(all_files) == 0:
        raise FileNotFoundError(f"No CSV or parquet files found under: {base_path}")

    print(f"Found {len(all_files)} files.\n")

    dfs = []
    for file in all_files:
        filename = os.path.basename(file).lower()

        if "copy of" in filename:
            print(f"Skipping duplicate file: {file}")
            continue

        try:
            if file.lower().endswith(".csv"):
                df = pd.read_csv(file)
            elif file.lower().endswith(".parquet"):
                df = pd.read_parquet(file)
            else:
                continue

            df.columns = df.columns.str.strip()
            dfs.append(df)
            print(f"Loaded: {file} -> {df.shape}")

        except Exception as e:
            print(f"Skipping: {file} | Error: {e}")

    if len(dfs) == 0:
        raise ValueError("Files were found, but none could be loaded successfully.")

    full_df = pd.concat(dfs, ignore_index=True)
    full_df.columns = full_df.columns.str.strip()

    print(f"\nCombined dataset shape: {full_df.shape}")
    return full_df


def find_target_column(df: pd.DataFrame, preferred_target: str = "label") -> str:
    """
    Find the target/label column safely.
    """
    possible_targets = [
        preferred_target, "label", "Label", "labels", "Labels",
        "Attack", "attack", "Class", "class"
    ]

    df_cols_lower = {col.lower(): col for col in df.columns}

    for col in possible_targets:
        if col.lower() in df_cols_lower:
            actual_col = df_cols_lower[col.lower()]
            print(f"Using target column: {actual_col}")
            return actual_col

    raise ValueError(
        f"Could not find a target column. Available columns are:\n{df.columns.tolist()}"
    )


def inspect_dataset(df: pd.DataFrame, target_col: str):
    print("\n===== DATASET OVERVIEW =====")
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    print("\nTarget value counts:")
    print(df[target_col].value_counts(dropna=False).head(30))
    print("\nMissing values (top 10):")
    print(df.isna().sum().sort_values(ascending=False).head(10))


def clean_dataset(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
    """
    Clean dataset and convert labels to binary:
    anything containing 'benign' -> 0
    everything else -> 1
    """
    df = df.copy()
    df.columns = df.columns.str.strip()

    raw_labels = df[target_col].astype(str).str.strip()
    print("\n===== RAW LABELS BEFORE BINARY MAPPING =====")
    print(raw_labels.value_counts().head(50))

    raw_labels_lower = raw_labels.str.lower()

    # This correctly maps 'BenignTraffic' -> 0
    df[target_col] = raw_labels_lower.apply(lambda x: 0 if "benign" in x else 1)

    before = len(df)
    df = df.drop_duplicates()
    after = len(df)
    print(f"\nRemoved duplicates: {before - after}")

    df = df.replace([np.inf, -np.inf], np.nan)

    print("\n===== TARGET DISTRIBUTION AFTER CLEANING =====")
    print(df[target_col].value_counts())

    return df


def split_features_target(df: pd.DataFrame, target_col: str):
    X = df.drop(columns=[target_col])
    y = df[target_col]
    return X, y


def keep_numeric_features_only(X: pd.DataFrame):
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    dropped_cols = [col for col in X.columns if col not in numeric_cols]

    if dropped_cols:
        print(f"\nDropped non-numeric columns: {dropped_cols}")

    X_numeric = X[numeric_cols].copy()
    return X_numeric, numeric_cols


def preprocess_features(X_train: pd.DataFrame, X_test: pd.DataFrame):
    numeric_cols = X_train.columns.tolist()

    imputer = SimpleImputer(strategy="median")
    scaler = StandardScaler()

    X_train_imputed = imputer.fit_transform(X_train)
    X_test_imputed = imputer.transform(X_test)

    X_train_scaled = scaler.fit_transform(X_train_imputed)
    X_test_scaled = scaler.transform(X_test_imputed)

    return X_train_scaled, X_test_scaled, numeric_cols, imputer, scaler


def mrmr_style_feature_selection(X_train, y_train, X_test, feature_names, top_k=20):
    """
    Mutual information-based feature ranking.
    """
    if len(np.unique(y_train)) < 2:
        raise ValueError("y_train contains only one class. Cannot perform feature selection.")

    mi_scores = mutual_info_classif(X_train, y_train, random_state=RANDOM_STATE)
    ranked_idx = np.argsort(mi_scores)[::-1][:top_k]

    selected_features = [feature_names[i] for i in ranked_idx]
    X_train_sel = X_train[:, ranked_idx]
    X_test_sel = X_test[:, ranked_idx]

    feature_df = pd.DataFrame({
        "Feature": feature_names,
        "MI_Score": mi_scores
    }).sort_values(by="MI_Score", ascending=False)

    feature_df.to_csv(OUTPUT_DIR / "feature_scores.csv", index=False)

    return X_train_sel, X_test_sel, selected_features, feature_df


def false_positive_rate(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    return fp / (fp + tn) if (fp + tn) > 0 else 0.0


def evaluate_model(model, X_train, y_train, X_test, y_test, model_name):
    start_train = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - start_train

    start_infer = time.time()
    y_pred = model.predict(X_test)
    infer_time = time.time() - start_infer

    y_prob = None
    roc_auc = np.nan

    if hasattr(model, "predict_proba"):
        probs = model.predict_proba(X_test)
        if probs.shape[1] > 1:
            y_prob = probs[:, 1]
            roc_auc = roc_auc_score(y_test, y_prob)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    fpr = false_positive_rate(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

    model_file = OUTPUT_DIR / f"{model_name}.joblib"
    joblib.dump(model, model_file)
    model_size_kb = os.path.getsize(model_file) / 1024

    results = {
        "Model": model_name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1,
        "False Positive Rate": fpr,
        "ROC-AUC": roc_auc,
        "Training Time (s)": train_time,
        "Inference Time (s)": infer_time,
        "Model Size (KB)": model_size_kb,
        "Confusion Matrix": cm.tolist()
    }

    return results, y_pred, y_prob, cm


def plot_confusion_matrix(cm, model_name):
    disp = ConfusionMatrixDisplay(
        confusion_matrix=np.array(cm),
        display_labels=["Benign", "Attack"]
    )
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix - {model_name}")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{model_name}_confusion_matrix.png")
    plt.show()


def plot_roc_curve(y_test, y_prob, model_name):
    if y_prob is None:
        print(f"ROC curve skipped for {model_name} (no valid probability scores).")
        return

    RocCurveDisplay.from_predictions(y_test, y_prob)
    plt.title(f"ROC Curve - {model_name}")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{model_name}_roc_curve.png")
    plt.show()


# ============================================================
# 4. MAIN PIPELINE
# ============================================================

def main():
    # --------------------------------------------------------
    # 1. Load full dataset
    # --------------------------------------------------------
    df = load_cic_iot2023_dataset(BASE_DATASET_PATH)

    # --------------------------------------------------------
    # 2. Find label column
    # --------------------------------------------------------
    actual_target_col = find_target_column(df, TARGET_COLUMN)

    # --------------------------------------------------------
    # 3. Inspect raw data
    # --------------------------------------------------------
    inspect_dataset(df, actual_target_col)

    # --------------------------------------------------------
    # 4. Clean and map labels
    # --------------------------------------------------------
    df = clean_dataset(df, actual_target_col)

    if df[actual_target_col].nunique() < 2:
        raise ValueError(
            "The dataset contains only one class after cleaning. "
            "Check the raw label names and binary mapping."
        )

    # --------------------------------------------------------
    # 5. Optional stratified sampling AFTER cleaning
    # --------------------------------------------------------
    if USE_SAMPLING:
        df = df.groupby(actual_target_col, group_keys=False).apply(
            lambda x: x.sample(frac=SAMPLE_FRAC, random_state=RANDOM_STATE)
        ).reset_index(drop=True)

        print(f"\n===== SAMPLED DATASET SHAPE =====")
        print(df.shape)
        print("\n===== TARGET DISTRIBUTION AFTER SAMPLING =====")
        print(df[actual_target_col].value_counts())

    # --------------------------------------------------------
    # 6. Split X and y
    # --------------------------------------------------------
    X, y = split_features_target(df, actual_target_col)

    # --------------------------------------------------------
    # 7. Keep numeric columns only
    # --------------------------------------------------------
    X, numeric_cols = keep_numeric_features_only(X)
    print(f"\nUsing {len(numeric_cols)} numeric features.")

    # --------------------------------------------------------
    # 8. Train-test split
    # --------------------------------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=y
    )

    print("\nTrain shape:", X_train.shape)
    print("Test shape:", X_test.shape)

    # --------------------------------------------------------
    # 9. Preprocessing
    # --------------------------------------------------------
    X_train_processed, X_test_processed, feature_names, imputer, scaler = preprocess_features(X_train, X_test)

    joblib.dump(imputer, OUTPUT_DIR / "imputer.joblib")
    joblib.dump(scaler, OUTPUT_DIR / "scaler.joblib")

    # --------------------------------------------------------
    # 10. Feature selection
    # --------------------------------------------------------
    X_train_sel, X_test_sel, selected_features, feature_df = mrmr_style_feature_selection(
        X_train_processed,
        y_train,
        X_test_processed,
        feature_names,
        top_k=TOP_K_FEATURES
    )

    print("\n===== SELECTED FEATURES =====")
    for i, f in enumerate(selected_features, start=1):
        print(f"{i}. {f}")

    pd.DataFrame({"Selected_Features": selected_features}).to_csv(
        OUTPUT_DIR / "selected_features.csv", index=False
    )

    # --------------------------------------------------------
    # 11. Define models
    # --------------------------------------------------------
    models = {
        "DecisionTree": DecisionTreeClassifier(
            max_depth=8,
            random_state=RANDOM_STATE
        ),
        "RandomForest": RandomForestClassifier(
            n_estimators=100,
            max_depth=12,
            random_state=RANDOM_STATE,
            n_jobs=-1
        ),
        "LogisticRegression": LogisticRegression(
            max_iter=1000,
            random_state=RANDOM_STATE
        ),
        "GradientBoosting": GradientBoostingClassifier(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=3,
            random_state=RANDOM_STATE
        )
    }

    # --------------------------------------------------------
    # 12. Train and evaluate
    # --------------------------------------------------------
    results = []
    confusion_records = []

    for model_name, model in models.items():
        print(f"\n===== TRAINING {model_name} =====")

        result, y_pred, y_prob, cm = evaluate_model(
            model,
            X_train_sel,
            y_train,
            X_test_sel,
            y_test,
            model_name
        )

        results.append(result)
        confusion_records.append({
            "Model": model_name,
            "Confusion Matrix": cm.tolist()
        })

        print(f"\nResults for {model_name}:")
        for key, value in result.items():
            if key != "Confusion Matrix":
                print(f"{key}: {value}")

        plot_confusion_matrix(cm, model_name)
        plot_roc_curve(y_test, y_prob, model_name)

    # --------------------------------------------------------
    # 13. Save final results
    # --------------------------------------------------------
    results_df = pd.DataFrame(results)
    results_df.to_csv(OUTPUT_DIR / "model_results.csv", index=False)

    cm_df = pd.DataFrame(confusion_records)
    cm_df.to_csv(OUTPUT_DIR / "confusion_matrices.csv", index=False)

    print("\n===== FINAL RESULTS TABLE =====")
    display_cols = [
        "Model", "Accuracy", "Precision", "Recall", "F1",
        "False Positive Rate", "ROC-AUC",
        "Training Time (s)", "Inference Time (s)", "Model Size (KB)"
    ]
    print(results_df[display_cols].sort_values(by="F1", ascending=False))

    # --------------------------------------------------------
    # 14. Save summary
    # --------------------------------------------------------
    best_model = results_df.sort_values(by="F1", ascending=False).iloc[0]
    summary_text = f"""
Best model based on F1-score: {best_model['Model']}
Accuracy: {best_model['Accuracy']:.4f}
Precision: {best_model['Precision']:.4f}
Recall: {best_model['Recall']:.4f}
F1: {best_model['F1']:.4f}
False Positive Rate: {best_model['False Positive Rate']:.4f}
ROC-AUC: {best_model['ROC-AUC']:.4f}
Training Time (s): {best_model['Training Time (s)']:.4f}
Inference Time (s): {best_model['Inference Time (s)']:.6f}
Model Size (KB): {best_model['Model Size (KB)']:.2f}
"""
    with open(OUTPUT_DIR / "summary.txt", "w") as f:
        f.write(summary_text)

    print("\nSaved all outputs to:", OUTPUT_DIR.resolve())
    print(summary_text)


# ============================================================
# 5. RUN
# ============================================================

if __name__ == "__main__":
    main()

# ============================================================
# LIGHTWEIGHT ML-BASED IDS FOR IOT ENVIRONMENTS
# MEMORY-OPTIMIZED COLAB VERSION
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os
import time
import glob
import joblib
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    RocCurveDisplay
)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

warnings.filterwarnings("ignore")

# ============================================================
# CONFIG
# ============================================================

BASE_DATASET_PATH = "/content/drive/MyDrive/CICIOT23"
TARGET_COLUMN = "label"

TEST_SIZE = 0.2
RANDOM_STATE = 42
TOP_K_FEATURES = 20

# much smaller sample to avoid Colab crash
ROWS_PER_FILE = 100000

OUTPUT_DIR = Path("/content/outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

# ============================================================
# HELPERS
# ============================================================

def load_sampled_cic_iot2023_dataset(base_path: str, rows_per_file: int = 100000) -> pd.DataFrame:
    """
    Load a manageable sample from each file instead of loading everything.
    """
    csv_files = glob.glob(os.path.join(base_path, "**", "*.csv"), recursive=True)
    parquet_files = glob.glob(os.path.join(base_path, "**", "*.parquet"), recursive=True)
    all_files = csv_files + parquet_files

    if len(all_files) == 0:
        raise FileNotFoundError(f"No CSV or parquet files found under: {base_path}")

    print(f"Found {len(all_files)} files.\n")

    dfs = []

    for file in all_files:
        filename = os.path.basename(file).lower()

        if "copy of" in filename:
            print(f"Skipping duplicate file: {file}")
            continue

        try:
            if file.lower().endswith(".csv"):
                df = pd.read_csv(file)
            else:
                df = pd.read_parquet(file)

            df.columns = df.columns.str.strip()

            if len(df) > rows_per_file:
                df = df.sample(n=rows_per_file, random_state=RANDOM_STATE)

            dfs.append(df)
            print(f"Loaded sampled: {file} -> {df.shape}")

        except Exception as e:
            print(f"Skipping: {file} | Error: {e}")

    if len(dfs) == 0:
        raise ValueError("No files could be loaded.")

    full_df = pd.concat(dfs, ignore_index=True)
    full_df.columns = full_df.columns.str.strip()

    print(f"\nCombined sampled dataset shape: {full_df.shape}")
    return full_df


def find_target_column(df: pd.DataFrame, preferred_target: str = "label") -> str:
    possible_targets = [
        preferred_target, "label", "Label", "labels", "Labels",
        "Attack", "attack", "Class", "class"
    ]

    df_cols_lower = {col.lower(): col for col in df.columns}

    for col in possible_targets:
        if col.lower() in df_cols_lower:
            actual_col = df_cols_lower[col.lower()]
            print(f"Using target column: {actual_col}")
            return actual_col

    raise ValueError(f"Could not find target column. Columns: {df.columns.tolist()}")


def inspect_dataset(df: pd.DataFrame, target_col: str):
    print("\n===== DATASET OVERVIEW =====")
    print("Shape:", df.shape)
    print("\nTarget value counts:")
    print(df[target_col].value_counts(dropna=False).head(30))
    print("\nMissing values (top 10):")
    print(df.isna().sum().sort_values(ascending=False).head(10))


def clean_dataset(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
    df = df.copy()
    df.columns = df.columns.str.strip()

    raw_labels = df[target_col].astype(str).str.strip()
    print("\n===== RAW LABELS BEFORE BINARY MAPPING =====")
    print(raw_labels.value_counts().head(50))

    raw_labels_lower = raw_labels.str.lower()
    df[target_col] = raw_labels_lower.apply(lambda x: 0 if "benign" in x else 1)

    before = len(df)
    df = df.drop_duplicates()
    after = len(df)
    print(f"\nRemoved duplicates: {before - after}")

    df = df.replace([np.inf, -np.inf], np.nan)

    print("\n===== TARGET DISTRIBUTION AFTER CLEANING =====")
    print(df[target_col].value_counts())

    return df


def split_features_target(df: pd.DataFrame, target_col: str):
    X = df.drop(columns=[target_col])
    y = df[target_col]
    return X, y


def keep_numeric_features_only(X: pd.DataFrame):
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    X_numeric = X[numeric_cols].copy()
    return X_numeric, numeric_cols


def preprocess_features(X_train: pd.DataFrame, X_test: pd.DataFrame):
    numeric_cols = X_train.columns.tolist()

    imputer = SimpleImputer(strategy="median")
    scaler = StandardScaler()

    X_train_imputed = imputer.fit_transform(X_train)
    X_test_imputed = imputer.transform(X_test)

    X_train_scaled = scaler.fit_transform(X_train_imputed)
    X_test_scaled = scaler.transform(X_test_imputed)

    return X_train_scaled, X_test_scaled, numeric_cols, imputer, scaler


def mrmr_style_feature_selection(X_train, y_train, X_test, feature_names, top_k=20):
    mi_scores = mutual_info_classif(X_train, y_train, random_state=RANDOM_STATE)
    ranked_idx = np.argsort(mi_scores)[::-1][:top_k]

    selected_features = [feature_names[i] for i in ranked_idx]
    X_train_sel = X_train[:, ranked_idx]
    X_test_sel = X_test[:, ranked_idx]

    feature_df = pd.DataFrame({
        "Feature": feature_names,
        "MI_Score": mi_scores
    }).sort_values(by="MI_Score", ascending=False)

    feature_df.to_csv(OUTPUT_DIR / "feature_scores.csv", index=False)

    return X_train_sel, X_test_sel, selected_features, feature_df


def false_positive_rate(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    return fp / (fp + tn) if (fp + tn) > 0 else 0.0


def evaluate_model(model, X_train, y_train, X_test, y_test, model_name):
    start_train = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - start_train

    start_infer = time.time()
    y_pred = model.predict(X_test)
    infer_time = time.time() - start_infer

    y_prob = None
    roc_auc = np.nan

    if hasattr(model, "predict_proba"):
        probs = model.predict_proba(X_test)
        if probs.shape[1] > 1:
            y_prob = probs[:, 1]
            roc_auc = roc_auc_score(y_test, y_prob)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    fpr = false_positive_rate(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

    model_file = OUTPUT_DIR / f"{model_name}.joblib"
    joblib.dump(model, model_file)
    model_size_kb = os.path.getsize(model_file) / 1024

    results = {
        "Model": model_name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1,
        "False Positive Rate": fpr,
        "ROC-AUC": roc_auc,
        "Training Time (s)": train_time,
        "Inference Time (s)": infer_time,
        "Model Size (KB)": model_size_kb
    }

    return results, y_pred, y_prob, cm


def plot_confusion_matrix(cm, model_name):
    disp = ConfusionMatrixDisplay(confusion_matrix=np.array(cm), display_labels=["Benign", "Attack"])
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix - {model_name}")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{model_name}_confusion_matrix.png")
    plt.show()


def plot_roc_curve(y_test, y_prob, model_name):
    if y_prob is None:
        return
    RocCurveDisplay.from_predictions(y_test, y_prob)
    plt.title(f"ROC Curve - {model_name}")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{model_name}_roc_curve.png")
    plt.show()


# ============================================================
# MAIN
# ============================================================

def main():
    df = load_sampled_cic_iot2023_dataset(BASE_DATASET_PATH, rows_per_file=ROWS_PER_FILE)

    actual_target_col = find_target_column(df, TARGET_COLUMN)
    inspect_dataset(df, actual_target_col)

    df = clean_dataset(df, actual_target_col)

    if df[actual_target_col].nunique() < 2:
        raise ValueError("Still only one class after cleaning.")

    X, y = split_features_target(df, actual_target_col)
    X, numeric_cols = keep_numeric_features_only(X)

    print(f"\nUsing {len(numeric_cols)} numeric features.")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=y
    )

    print("\nTrain shape:", X_train.shape)
    print("Test shape:", X_test.shape)

    X_train_processed, X_test_processed, feature_names, imputer, scaler = preprocess_features(X_train, X_test)

    joblib.dump(imputer, OUTPUT_DIR / "imputer.joblib")
    joblib.dump(scaler, OUTPUT_DIR / "scaler.joblib")

    X_train_sel, X_test_sel, selected_features, feature_df = mrmr_style_feature_selection(
        X_train_processed, y_train, X_test_processed, feature_names, top_k=TOP_K_FEATURES
    )

    print("\n===== SELECTED FEATURES =====")
    for i, f in enumerate(selected_features, start=1):
        print(f"{i}. {f}")

    models = {
        "DecisionTree": DecisionTreeClassifier(max_depth=8, random_state=RANDOM_STATE),
        "RandomForest": RandomForestClassifier(n_estimators=100, max_depth=12, random_state=RANDOM_STATE, n_jobs=-1),
        "LogisticRegression": LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
        "GradientBoosting": GradientBoostingClassifier(n_estimators=50, learning_rate=0.1, max_depth=3, random_state=RANDOM_STATE)
    }

    results = []

    for model_name, model in models.items():
        print(f"\n===== TRAINING {model_name} =====")
        result, y_pred, y_prob, cm = evaluate_model(
            model, X_train_sel, y_train, X_test_sel, y_test, model_name
        )

        results.append(result)

        print(f"\nResults for {model_name}:")
        for key, value in result.items():
            print(f"{key}: {value}")

        plot_confusion_matrix(cm, model_name)
        plot_roc_curve(y_test, y_prob, model_name)

    results_df = pd.DataFrame(results)
    results_df.to_csv(OUTPUT_DIR / "model_results.csv", index=False)

    print("\n===== FINAL RESULTS TABLE =====")
    print(results_df.sort_values(by="F1", ascending=False))
    results.append(result)
    if model_name == "GradientBoosting":
      joblib.dump(model, "gb_ids_model.pkl")

  # Create deployment sample
    sample_data = pd.DataFrame(X_test_sel[:10], columns=selected_features)

    # Save actual labels
    sample_labels = pd.DataFrame(y_test.iloc[:10].values, columns=["Actual_Label"])

    # Export files
    sample_data.to_csv("deployment_test.csv", index=False)
    sample_labels.to_csv("deployment_labels.csv", index=False)

    print("Deployment files created!")

if __name__ == "__main__":
    main()